
[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace]
members = ["app/*", "crates/*"]
resolver = "2"


[workspace.dependencies]
axum = { version = "0.7" }
async-trait = "0.1"
tokio = { version = "1" }

serde = { version = "1" }
serde_json = "1"

strum = "0.26"
strum_macros = "0.26"
thiserror = "2.0.18"

validator = { version = "0.18", features = ["derive"] }

config = { version = "0.15.22" }
chrono = { version = "0.4", features = ["serde"] }
humantime = "2"

bcrypt = "0.19.0"
jsonwebtoken = "9"

# db
sqlx = { version = "0.8", features = [
    "postgres",
    "runtime-tokio",
    "uuid",
    "chrono",
    "macros",
] }
uuid = { version = "1", features = ["v4", "serde"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.5", features = ["trace"] }

anyhow = { version = "1" }
