# port: 3002

db:
  url: postgres://postgres:changeme@localhost:5433/todo

jwt:
  secret: secret
  deadline: 24h

# messaging:
#   provider: nats
#   url: nats://localhost:4222

messaging:
  provider: rabbitmq
  url: amqp://user:password@localhost:5672