[package]
name = "extractors"
version.workspace = true
edition.workspace = true

[dependencies]
jsonwebtoken = { workspace = true }
axum = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

errors = { path = "../errors" }
auth_jwt = { path = "../auth_jwt" }
