[package]
name = "entities"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

chrono = { workspace = true }

strum = { workspace = true }
strum_macros = { workspace = true }
sea-orm = { workspace = true }
