[package]
name = "user-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
config = { workspace = true }
bcrypt = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
humantime = { workspace = true }

# db
sqlx = { workspace = true }
uuid = { workspace = true }
