[package]
name = "notification-service"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

settings = { path = "../../crates/settings" }
errors = { path = "../../crates/errors" }
messaging = { path = "../../crates/messaging" }
entities = { path = "../../crates/entities" }

anyhow.workspace = true
